*------------------------------------------------------------------*
* Author........: Martín Salías
* Date..........: April 15, 2005
*)Notes.........: Demo Logo application
*)              : Specialized for the Demo App
* See also......: 
*
Define Class DemoLogo as AppLogo of ..\Comun\AppLogo.prg
	
	Picture = "Source\taLogo.Gif"
	Anchor = 15  && Top/Bottom - Left/Right
	BorderStyle = 0
	Stretch = 0

EndDefine

*------------------------------------------------------------------*
